### ISSUE TITLE
Debug-Ausgaben im Contao System-Log

### ISSUE THREAD

**Issue by xchs** [timgatzky/pct_customelements_plugin_cc_frontedit#35]
Contao 3.5.28
Aktuelle Versionen von PCT CustomElements und PCT CustomCatalog

Im Frontend ist ein Modul CustomCatalog-Liste eingebunden, das die Datenätze entsprechend gefiltert ausgeben soll. Bei jedem Frontend-Aufruf wird allerdings im Contao System-Log der komplette SQL SELECT Query protokolliert. Aufgrund der Länge des Strings sprengt das natürlich das Layout im System-Log.

![cc](https://user-images.githubusercontent.com/1218766/28621123-2cec033c-7210-11e7-8226-0769165a8f9c.png)

Ich wollte diese Debug-Ausgaben per
```php
$GLOBALS['PCT_CUSTOMCATALOG']['debug'] = false;
```
in der `localconfig.php` komplett deaktivieren, aber offenbar hat das keine Auswirkungen.

**Comment by timgatzky** [comment]
Gehört hier zwar nicht her, aber der Standard ist KEINE Ausgabe. Du wirst irgendwo noch die Globale gesetzt haben.

**Comment by xchs** [comment]
> Gehört hier zwar nicht her

Sorry, stimmt. Gibt es für den CC kein (öffentliches) Repository hier auf GitHub oder habe ich das nur übersehen?


> Du wirst irgendwo noch die Globale gesetzt haben: dcaconfig? initconfig? eigene Erw.? vielleicht in einem Template?

Vielen Dank. Du hattest recht! In der `initconfig.php` hatte jemand die Debug-Ausgabe aktiviert gehabt. Ich hatte zuvor leider nur in der `localconfig.php` nachgeschaut, ob dort irgendwo `$GLOBALS['PCT_CUSTOMCATALOG']['debug'] = true;` gesetzt ist (was offensichtlich nicht der Fall war).

**Comment by timgatzky** [comment]
Bei PCT direkt ist ein öffentliches: https://github.com/premiumcontaothemes/customcatalog
Aber am meisten nutzen wir einfach unser Forum für CC: http://forum.premium-contao-themes.com/forum/module/customcatalog
