### ISSUE TITLE
Problem with Checkboxes in Contao 4

### ISSUE THREAD

**Issue by SGehle** [timgatzky/pct_customelements_plugin_cc_frontedit#46]
Because of the Mootools toggle_select Checkboxes can not be checked in the pct_tabletree_widget iFrame. Is there any Solution? Thanks!

**Comment by timgatzky** [comment]
I know. Always being like this. Klick the whole list element or slightly next to the checkbox (right side)

**Comment by SGehle** [comment]
Works in the Demo...

**Comment by SGehle** [comment]
Demo is Contao 3.5 - only problem in Contao 4? Solution?

**Comment by timgatzky** [comment]
As i said, click in the list element or slightly next to the checkbox.
