### ISSUE TITLE
Problem after Tag Manager Reload

### ISSUE THREAD

**Issue by SGehle** [timgatzky/pct_customelements_plugin_cc_frontedit#47]
After saving Tag-Selections with pct_tabletree_widget - the whole page is loaded with ajax in Contao 4.4.19

![error](https://user-images.githubusercontent.com/1748990/41658597-27f13444-7497-11e8-9088-4625fc93b0ec.png)

**Comment by timgatzky** [comment]
Are there any JS-errors in the console?
I don't have that issue / reproduce that issue in any of our installations

**Comment by SGehle** [comment]
Uncaught DOMException: Blocked a frame with origin "" from accessing a cross-origin frame.
    at Object.<anonymous> (assets/js/ae876f46e976.js:110:16)
    at HTMLAnchorElement.a (assets/mootools/js/mootools.min.js:1:61896)

**Comment by timgatzky** [comment]
Mhh... crossdomain rights should not be broken here. Even not in the iframe

**Comment by timgatzky** [comment]
Tested it here: http://cc.unlimited-c4.premium-contao-themes.com/liste-2200.html, no problems

**Comment by SGehle** [comment]
Tested it here: http://cc.unlimited-c4.premium-contao-themes.com/liste-2200.html, same Problem. 
Chrome 67.0.3396.99

**Comment by SGehle** [comment]
http://cc.feedit.premium-contao-themes.com/detail.html - Same problem

**Comment by timgatzky** [comment]
No issues for me on the following browsers: Chrome, FF, Safari on Mac
I don't have a Windows machine.

btw. how can you test these things in the unlimited demo, when fe editing is not enabled.

ps. I think we can speak German. :)

**Comment by timgatzky** [comment]
Kannst du mehr Informationen geben. Welches System nutzt du usw. Chrome allein reicht nicht. Windows, Mac, welches Betriebssystem. Mach ein Video

**Comment by SGehle** [comment]
Windows 10, Chrome 67.0.3396.99
![20180705_094518](https://user-images.githubusercontent.com/1748990/42309450-e25ce966-8038-11e8-881f-0a5732c74e05.gif)

**Comment by timgatzky** [comment]
Might be fixed with #71
