### ISSUE TITLE
PID fehlt in Url nach "switchToEdit" Event

### ISSUE THREAD

**Issue by timgatzky** [timgatzky/pct_customelements_plugin_cc_frontedit#77]

**Comment by SGehle** [comment]
Hier wird der pid-Parameter ignoriert: https://github.com/contao/core-bundle/commit/4c3586d157160ce9eff07ca346040c2f578b758a

**Comment by timgatzky** [comment]
Sehr gut recherchiert. 
Ich musste ebenfalls den PID händisch nachfeuern in einer Applikation.

**Comment by SGehle** [comment]
Ich habe in dem entsprechenden Ticket mal gefragt, aber bis jetzt keine Antwort erhalten.
Wäre es möglich, den Namen des Parameters in parent_id zu ändern? Dann würde dieser nicht mehr entfernt werden...

**Comment by timgatzky** [comment]
Damit halsen wir uns nur neue Probleme auf für die Listen-Ansichten etc.

**Comment by SGehle** [comment]
Oder könnte die pid in der Session gespeichert werden? 
So würde auch bei fehlendem pid Parameter der Eintrag korrekt angelegt und Kind-Listen-Ansichten würden auch ohne Parameter korrekt dargestellt.
