### ISSUE TITLE
Support "existing" Tables in ModuleReader

### ISSUE THREAD

**Issue by timgatzky** [timgatzky/pct_customelements_plugin_cc_frontedit#80]

**Comment by timgatzky** [comment]
Das wird gar nicht so leicht. Die Auswahl des CCs speichert den Tabellennamen. Bei mehreren CCs, die z.B. tl_member erweitertern, bekommt man in der Auswahl schon nur noch den letzten. 
Ich denke hier braucht es mittelfristig einen Umbau auf Speicherung der CC-Konfig-ID als Referenz anstelle des Tabellennamens

**Comment by SGehle** [comment]
Ich habe eine relativ einfach Änderung an der CustomCatalogFactory.php des pct_customelements_plugin_customcatalog gemacht - diese gibt es ja (logischerweise) hier nicht. 
Ab Zeile 201:

`public static function findByTableName($strTable)
	{
		\System::log('xxy', __METHOD__, TL_GENERAL);
		if(strlen($strTable) < 1)
		{
			\System::log('aa', __METHOD__, TL_GENERAL);
			return null;
			
		}
		
		if(Cache::getCustomCatalog($strTable) !== null)
		{
			\System::log('a', __METHOD__, TL_GENERAL);
			return Cache::getCustomCatalog($strTable);
			
		}
		
		$objModel = CustomCatalogModel::findByTableName($strTable);
		if($objModel === null)
		{
			$objModel = CustomCatalogModel::findBy('existingTable',$strTable);
			
		}
		\System::log('c', __METHOD__, TL_GENERAL);
		$objReturn = static::create( $objModel );
		if($objReturn === null)
		{
			return null;
			\System::log('c', __METHOD__, TL_GENERAL);
		}
		
		// add to cache
		Cache::addCustomCatalog($objReturn->id, $objReturn);
		Cache::addCustomCatalog($strTable, $objReturn);

		return $objReturn;
	}`

Die Anpassung müsste man dann für die anderen Find-Methoden auch noch anpassen.

**Comment by SGehle** [comment]
Ich habe die Methode findByTableName der CustomCatalogFactory des pct_customelements_plugin_customcatalog angepasst:

`public static function findByTableName($strTable)
	{
		if(strlen($strTable) < 1)
		{
			return null;
			
		}
		
		if(Cache::getCustomCatalog($strTable) !== null)
		{
			return Cache::getCustomCatalog($strTable);
			
		}
		
		$objModel = CustomCatalogModel::findByTableName($strTable);
		if($objModel === null)
		{
			$objModel = CustomCatalogModel::findBy('existingTable',$strTable);
			if($objModel === null)
			{
				return null;
			}
			
		}
		$objReturn = static::create( $objModel );
		if($objReturn === null)
		{
			return null;
		}
		
		// add to cache
		Cache::addCustomCatalog($objReturn->id, $objReturn);
		Cache::addCustomCatalog($strTable, $objReturn);

		return $objReturn;
	}`

So könnte man dann die anderen Find-Methoden auch anpassen.

**Comment by SGehle** [comment]
Alternativ könnte man auch die Find-Methoden im CustomCatalogModel umschreiben...

**Comment by timgatzky** [comment]
Danke Dir für die Mühe, so können wir es aber leider nicht machen - auch wenn es der Weg des geringsten Widerstandes wäre. CC erlaubt mehrere Konfigurationen zu haben auf existierenden Tabellen. Damit würde in diesem Fall nur die letzte in der Kette korrekt registriert.
Ich habe für CCs kommende Major Version den Umbau auf IDs bereits vorgenommen für die Auswahl der Konfiguration in den Liste/Leser Modulen. Damit sind wir save.

**Comment by SGehle** [comment]
Umso besser, freut mich!
